project:
  type: website
  output-dir: docs
  
website:
  title: "Sana Gupta's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About.qmd
      - projects.qmd
      - Crosswords.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/sana-gupta3/
      - icon: twitter
        href: https://x.com/sanaguptaaa
      - icon: github
        href: https://github.com/Sana-Gupta3
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "Last Updated: December 2024"

format:
  html:
    theme: darkly
    toc: true

editor: source

